name: Release artifact Build

on:
  release:
    types: [published]
    
env:
  ARCHITECTURES: win-x64;win-arm64;linux-x64;linux-musl-x64;linux-arm;osx-x64

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      shell: bash
      working-directory: KrisMecn
      run: |
        mkdir output
        for arch in $(echo $ARCHITECTURES | tr ";" "\n")
        do
          dotnet publish --configuration Release --runtime $arch --output $arch --self-contained false
          cd $arch/ && tar -zcvf ../output/kris-mecn-${GITHUB_REF##*/}-$base.tar.gz * && cd -
        done
  publish-to-release:
    needs: [build-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add artifacts to release
        uses: Roang-zero1/github-upload-release-artifacts-action@v2.1.0
        with:
          args: KrisMecn/output/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
